### ISSUE TITLE
include('dir/Kyuafile'), dir cannot be an absolute path

### ISSUE THREAD

**Issue by rodrigc** [jmmv/kyua#114]
Hi,

In the Kyuafile.5 man page: http://manned.org/kyuafile.5, there is this:

  -- Recurse into any subdirectories that may have other tests.
  include('dir1/Kyuafile')
  include('dir2/Kyuafile')

It looks like dir1 and dir2 cannot be an absolute path.
Can you remove this restriction?

I have an existing codebase, where unit tests are scattered in different places
in the tree.

I am trying to do something like create a parallel directory structure of just testsuites:

```
/tests/suite1/Kyuafile
/tests/suite2/Kyuafile
```

Inside /tests/suite1/Kyuafile, I have:

```
syntax(2)

include('/feature1/bin/prog1/Kyuafile')
include('/feature1/bin/prog2/Kyuafile')
```

If I do, 
cd /tests/suite1/
kyua test

I get:
    kyua: E: Load of 'Kyuafile' failed: Failed to load Lua file 'Kyuafile': Kyuafile:4: Load of /feature1/bin/prog1/Kyuafile'  Cannot join paths '.' and '/feature1/bin/prog1/mytest.sh': Cannot concatenate a path to an absolute path.

In the /feature1/bin/prog1 directory, I have a Kyuafile with:

```
syntax(2)

test_suite('suite1')

plain_test_program{name='mytest.sh'}
```

It would be helpful to be able to create a Kyuafile which includes Kyuafiles in different directories
which are absolute paths, to create different test suites.

**Comment by jmmv** [comment]
Nope; this is by design. Test suites have to be contained and rooted at a single directory. We use the file system layout to identify where a test suite lives and what's part of it. The way the interface exposes paths to tests and the way the internals are structured requires this: you provide a root directory to Kyua (in the form of `-k /usr/tests/Kyuafile` for example) and all tests executed are relative descendants of that.

You can game this by using symlinks like we do to expose `/usr/local/tests` via `/usr/tests/local` in FreeBSD. This works fine and allows maintaining the internal data model of Kyua.

**Comment by jmmv** [comment]
Keeping open to update the documentation to explain this in more detail. (Hit the wrong button previously...)

**Comment by rodrigc** [comment]
I understand your design decision.

However, on really big projects (not necessarily open source), you may have
tests which have been developed by multiple teams which are not in a single directory hierarchy.
This is actually highly likely.

In such an environment, you may need to put together multiple testing scenarios that
reuse tests in certain directories.

## SUITES

src/suite/regression/Kyuafile
src/suite/feature1/Kyuafile
src/suite/feature2/Kyuafile

## TESTS

src/bin/prog1/Kyuafile
src/usr.bin/prog2/Kyuafile
src/lib/libfoo/Kyuafile
src/test4/Kyuafile

The regression suite may span all 4 tests.
The feature1 suite, may include 3 out of the 4.
The feature2 suite may include 2 out of the 4 tests.

Can this be accomplished in any other way than symlinks?
Moving all the tests around, or significantly changing the build system is not something
I can do for starters.

Ideally this should be as easy to integrate with an existing codebase (which may not be perfectly clean
or well structured).  Otherwise it it is harder to promote Kyua in large existing codebases.

**Comment by jmmv** [comment]
I cannot change the behavior of Kyua because the reliance on the file system to describe the layout of a test suite is engraved in the design.

What I have done is improve the kyuafile(5) manpage to clearly describe this and I have added a detailed example describing how you can connect disjoint test suites into a single one. Symlinks and the sample Kyuafile.top distributed by Kyua should easily do the trick.
