### ISSUE TITLE
kyua stacktrace tests on Ubuntu 14.04 fail if apport is enabled

### ISSUE THREAD

**Issue by rodrigc** [jmmv/kyua#121]
I was testing kyua on Ubuntu 14.04, and some of the stacktrace
tests were failing because it could not find corefiles for certain tests.
I looked into it for a while, and found the following.

```
# cat /proc/sys/kernel/core_pattern
|/usr/share/apport/apport %p %s %c %P
```

Looking here: https://wiki.ubuntu.com/Apport

I found that this is a Python script on Ubuntu systems that intercepts user coredumps and generates some sort of report.

I disabled it by:

(1)  edit /etc/defaults/apport

```
set enabled=0
```

(2)  sudo service apport stop

I looked at the `core_pattern`:

```
# cat /proc/sys/kernel/core_pattern
core
```

When I re-ran all the kyua tests, the stacktrace tests then passed.

**Comment by jmmv** [comment]
More generally: obtaining stacktraces automatically does not work if the core_pattern involves executing an external program. In other words: this is not about failing _tests_; this is about functionality simply not working.

**Comment by rodrigc** [comment]
I don't see a good way to fix this problem other than putting a lot of Linux-specific code
in kyua to detect aspects of the system configuration which affects the generation of corefiles.
Keeping this issue in github (even if closed) so that people can find via web search might be good enough.....

**Comment by jmmv** [comment]
Well, one thing we can do is detect if `core_pattern` starts with `|` and, if so, make the stacktrace generation code warn that it's not able to do its job.  (Because, in that case, there is nothing we can do to know what happens to the core file.)

Note that there is also #106 on a similar topic.

**Comment by rodrigc** [comment]
Sure that would work.

**Comment by jmmv** [comment]
See my update to #106. What I said in my previous message does not make sense: finding the core file can fail for many more reasons than `core_pattern` being set to a pipe, so implementing a check for `|` would just cover one case and still leave others broken.

We should make the whole thing properly tell the user what's wrong when the core file cannot be opened, maybe just whitelisting the few cases that we can handle (so that we can explicitly differentiate between "we know that the core file should be there but cannot find it" vs. "we know a core was dumped but there is no way we can locate it".)

Closing in favor of #106 as the solution to both issues is the same.
