### ISSUE TITLE
kyua-* manpage headings are a bit confusing

### ISSUE THREAD

**Issue by ngie-eign** [jmmv/kyua#83]
man kyua-test prints out "test" for the command instead of the full command "kyua test". If someone wasn't looking at the heading of the manpage they might confuse this command with the built-in, "test":

<pre>
KYUA-TEST(1)            FreeBSD General Commands Manual           KYUA-TEST(1)

NAME
     test -- Runs tests

SYNOPSIS
     test [--build-root path] [--kyuafile file] [--store file]
          [test_filter1 .. test_filterN]
</pre>

This seems to be the case for other manpages as well, like kyua-build-root and kyua-list.

**Comment by jmmv** [comment]
How do you suggest to fix this? Changing the page name to `kyua-test` may be confusing as well because this page lives in section 1 and there is no command with that name.

But I guess that's probably a lesser evil, considering that, for example, git's manual pages do that. Using the same style, the page name would read `kyua-test` but the synopsis would mention `kyua test`. Sounds like a good compromise to me.

**Comment by jmmv** [comment]
Never mind. Found out yesterday (by looking at pkg's manual pages) that .Nm can include spaces.

**Comment by ngie-eign** [comment]
Thanks :)!
