### ISSUE TITLE
Pass configuration variables to non-ATF test programs via the environment

### ISSUE THREAD

**Issue by ngie-eign** [jmmv/kyua#84]
It would be nice if there was a way to require environment variables to be set in the environment and passed down to the test application/suite, as I noted in this pull request: https://github.com/yaneurabeya/freebsd/pull/4 . This would allow test programs/suites to be driven by ATF in a way that normally would be provided via command line options or by forcing Kyua to behave in a certain way (in this case cd'ing into a particular directory before running pjdfstest because that's how the tests were written).

**Comment by ngie-eign** [comment]
I've given this more thought and it makes more sense to create an atf-config-like tool (kyua-config?) for grabbing information from the UI (provided by the Kyuafile/command line with -v) that can be later queried to get the value of variables.

This is part of the gist behind the request I made on freebsd-testing last week: http://lists.freebsd.org/pipermail/freebsd-testing/2014-June/000439.html

**Comment by jmmv** [comment]
I don't think relying on environment variables for the configuration of the tests is a good idea...

Kyua supports the concept of per-test-suite configuration variables (see kyua.conf) and that's how configuration properties have to be passed to test programs.

Now... the problem is that, at the moment, only ATF-based test programs can query such variables! Plain test programs can't and that's what we ought to fix. For plain test programs, a possibility would be for Kyua to convert the configuration variables to environment variables using some predefined conventions. This way, plain test programs could access the variables without the need of any special libraries nor APIs.

**Comment by ngie-eign** [comment]
Agreed. If there was a way to prefix the environment variables with kyua_, kyua_tap_, etc, and export it to test apps, it would be really nice and easy to integrate test applications in to Kyua with "test drivers" to guide the code to do the right thing (TM).

**Comment by jmmv** [comment]
Let's do that then. For a given configuration property X (defined in kyua.conf as test_suites.SUITE_NAME.X), make its environment variable be TEST_ENV_${X} and set that when executing the test program.

The name of the test suite doesn't matter here because a given test program will always be tagged with the same test suite name and thus its set of configuration variables doesn't change.

I'd also not encode KYUA_ in the variable name. Plain test programs, for example, don't care about being executed by Kyua or something else -- so I'd rather keep them agnostic of who the executor is.

**Comment by ngie-eign** [comment]
On Thu, Jul 24, 2014 at 12:34 PM, Julio Merino notifications@github.com
wrote:

> Let's do that then. For a given configuration property X (defined in
> kyua.conf as test_suites.SUITE_NAME.X), make its environment variable be
> TEST_ENV_${X} and set that when executing the test program.
> 
> Would SUITE_NAME be FreeBSD? If so, couldn't this conflict if two "test
> scripts"/"test programs" wanted to access similarly named variables, e.g.
> TMPDIR, etc?

What if the values are set from the master kyua.conf ?

> The name of the test suite doesn't matter here because a given test
> program will always be tagged with the same test suite name and thus its
> set of configuration variables doesn't change.
> 
> I'd also not encode KYUA_ in the variable name. Plain test programs, for
> example, don't care about being executed by Kyua or something else -- so
> I'd rather keep them agnostic of who the executor is.
> 
> Good point!

**Comment by jmmv** [comment]
> Would SUITE_NAME be FreeBSD? If so, couldn't this conflict if two "test
> scripts"/"test programs" wanted to access similarly named variables, e.g.
> TMPDIR, etc?

Nope. The way things work today, you assign a test program to a test suite via the test_suite('foo') stanza in the Kyuafile. The only point of this definition is to map which variables from the Kyua configuration file are passed to the test program.

In other words: when you define test_suite('foo'), Kyua will search for any configuration variables in the test_suites.foo.\* "namespace" and pass those to the test. A variable called test_suites.foo.bar will then be seen by the ATF tests (via the atf_tc_config_get function) as a variable simply called "bar".

If you have two test programs that accept a TMPDIR variable, they will only share the value given by the user if you register both under the same test suite from the Kyuafile.
