### ISSUE TITLE
atf-c/utils.c:atf_utils_wait is not multiprocess/multithreading safe

### ISSUE THREAD

**Issue by ngie-eign** [jmmv/kyua#87]
This code is writing to a non-temporary file with a constant filename in order to capture the exec output. This is not multiprocess/multithreading safe:

<pre>
381 void
382 atf_utils_wait(const pid_t pid, const int exitstatus, const char *expout,
383                const char *experr)
384 {
385     int status;
386     ATF_REQUIRE(waitpid(pid, &status, 0) != -1);
387
388     atf_utils_cat_file("atf_utils_fork_out.txt", "subprocess stdout: ");
389     atf_utils_cat_file("atf_utils_fork_err.txt", "subprocess stderr: ");
390
391     ATF_REQUIRE(WIFEXITED(status));
392     ATF_REQUIRE_EQ(exitstatus, WEXITSTATUS(status));
393
394     const char *save_prefix = "save:";
395     const size_t save_prefix_length = strlen(save_prefix);
396
397     if (strlen(expout) > save_prefix_length &&
398         strncmp(expout, save_prefix, save_prefix_length) == 0) {
399         atf_utils_copy_file("atf_utils_fork_out.txt",
400                             expout + save_prefix_length);
401     } else {
402         ATF_REQUIRE(atf_utils_compare_file("atf_utils_fork_out.txt", expout));
403     }
404
405     if (strlen(experr) > save_prefix_length &&
406         strncmp(experr, save_prefix, save_prefix_length) == 0) {
407         atf_utils_copy_file("atf_utils_fork_err.txt",
408                             experr + save_prefix_length);
409     } else {
410         ATF_REQUIRE(atf_utils_compare_file("atf_utils_fork_err.txt", experr));
411     }
412
413     ATF_REQUIRE(unlink("atf_utils_fork_out.txt") != -1);
414     ATF_REQUIRE(unlink("atf_utils_fork_err.txt") != -1);
415 }
</pre>

**Comment by jmmv** [comment]
There is currently no expectation for the ATF interface to be thread-safe.

But the problem here is not about threads: it's about multiprocessing. It's perfectly reasonable to spawn to subprocess and wait for them with checks, which fails with the current fork/wait interface.

As an easy solution, we can tag the generated file names with the spawned PID. Not completely bug-free if the OS decides to reuse PIDs along the way, but most decent OSs nowadays will avoid immediate PID reuse to prevent certain types of attacks.

**Comment by jmmv** [comment]
Oops, this is actually an ATF issue so moved to https://github.com/jmmv/atf/issues/15 .
