### ISSUE TITLE
atf-sh-api(3) doesn't mention atf-check(1)

### ISSUE THREAD

**Issue by ngie-eign** [jmmv/kyua#98]
atf-sh-api(3) mentions atf_check, but it doesn't reference atf-check(1), which could be helpful for folks getting started with atf.

**Comment by jmmv** [comment]
The tool and manpage are mentioned under the "Helper functions for common checks" section. Feel free to add the reference to "See also" as well.

**Comment by jmmv** [comment]
It does where `atf_check` is explained, but not in SEE ALSO.

The naming distinction between `atf-check` and `atf_check` is a bit unfortunate. Trying to run `atf-check` directly from test cases won't work because `atf-check` is installed in `libexec`, which is intended, so displaying the `atf-check` manpage more prominently would confuse users unless they also see the mention of `atf_check`.

If doing this, we'd need to change `atf-check` to clearly explain that it cannot be executed explicitly.

Another alternative would be to add a manpage for `atf_check` itself and maybe remove the one for `atf-check`.

**Comment by jmmv** [comment]
This is an atf issue so moved to https://github.com/jmmv/atf/issues/12.
